#Connection to DB
spring: 
  datasource: 
    url: jdbc:sqlserver://localhost;databasename=CAVE_A_VIN;integratedSecurity=false;encrypt=false;trustServerCertificate=false
    username: sa
    password: Pa$$w0rd

#Options to DB
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: create